// Generated by extendr: Do not edit by hand.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let wrapper_path = "../R/extendr-wrappers.R";
    let header = "\
        # Generated by extendr: Do not edit by hand\n\
        # nolint start\n\
        \n\
        #' @usage NULL\n\
        #' @useDynLib arity, .registration = TRUE\n\
        NULL\n\
        \n\
    ";
    let footer = "# nolint end\n";
    let wrappers = arity::get_arity_metadata()
        .make_r_wrappers(true, "arity")
        .map_err(|error| format!("failed to generate wrappers: {error}"))?;
    std::fs::write(wrapper_path, format!("{header}{wrappers}{footer}"))
        .map_err(|error| format!("failed to write {wrapper_path}: {error}"))?;
    Ok(())
}
