use std::fs;

use arity_formatter::parser::ParseOptions;
use arity_formatter::{FormatStyle, LineEnding, format_verified_with_options, format_with_options};
use extendr_api::prelude::*;

const MIN_WIDTH: i32 = 1;
const MAX_WIDTH: i32 = 1000;

fn parse_width(value: i32, name: &str) -> extendr_api::Result<usize> {
    if !(MIN_WIDTH..=MAX_WIDTH).contains(&value) {
        return Err(
            format!("`{name}` must be from {MIN_WIDTH} through {MAX_WIDTH}, got {value}").into(),
        );
    }
    Ok(value as usize)
}

fn parse_line_ending(value: &str) -> extendr_api::Result<LineEnding> {
    match value {
        "auto" => Ok(LineEnding::Auto),
        "lf" => Ok(LineEnding::Lf),
        "crlf" => Ok(LineEnding::Crlf),
        "native" => Ok(LineEnding::Native),
        _ => Err(format!(
            "`line_ending` must be one of \"auto\", \"lf\", \"crlf\", or \"native\", got {value:?}"
        )
        .into()),
    }
}

fn format_source(
    source: &str,
    line_width: i32,
    indent_width: i32,
    line_ending: &str,
    roxygen_markdown: bool,
    verify: bool,
) -> extendr_api::Result<String> {
    let style = FormatStyle {
        line_width: parse_width(line_width, "line_width")?,
        indent_width: parse_width(indent_width, "indent_width")?,
        line_ending: parse_line_ending(line_ending)?,
    };
    let options = ParseOptions::default().with_roxygen_markdown_default(roxygen_markdown);

    if verify {
        format_verified_with_options(source, style, &options)
            .map_err(|error| format!("failed to format R source: {error}").into())
    } else {
        format_with_options(source, style, &options)
            .map_err(|error| format!("failed to format R source: {error}").into())
    }
}

/// Format one R source string.
/// @keywords internal
#[extendr]
fn format_text_native(
    source: &str,
    line_width: i32,
    indent_width: i32,
    line_ending: &str,
    roxygen_markdown: bool,
    verify: bool,
) -> extendr_api::Result<String> {
    format_source(
        source,
        line_width,
        indent_width,
        line_ending,
        roxygen_markdown,
        verify,
    )
}

/// Format one UTF-8 file in place and report whether it changed.
/// @keywords internal
#[extendr]
fn format_file_native(
    path: &str,
    line_width: i32,
    indent_width: i32,
    line_ending: &str,
    roxygen_markdown: bool,
    verify: bool,
) -> extendr_api::Result<bool> {
    let source = fs::read_to_string(path).map_err(|error| {
        if error.kind() == std::io::ErrorKind::InvalidData {
            Error::from(format!("failed to read `{path}`: file is not valid UTF-8"))
        } else {
            Error::from(format!("failed to read `{path}`: {error}"))
        }
    })?;
    let formatted = format_source(
        &source,
        line_width,
        indent_width,
        line_ending,
        roxygen_markdown,
        verify,
    )?;

    if formatted == source {
        return Ok(false);
    }

    fs::write(path, formatted.as_bytes())
        .map_err(|error| Error::from(format!("failed to write `{path}`: {error}")))?;
    Ok(true)
}

// Generated by rextendr::document().
extendr_module! {
    mod arity;
    fn format_text_native;
    fn format_file_native;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verified_and_single_pass_formatting_agree() {
        let source = "x<-(1+2)*3^4\n";
        let verified = format_source(source, 80, 2, "auto", false, true).unwrap();
        let single = format_source(source, 80, 2, "auto", false, false).unwrap();

        assert_eq!(verified, "x <- (1 + 2) * 3^4\n");
        assert_eq!(single, verified);
    }

    #[test]
    fn native_validation_rejects_invalid_options() {
        assert!(format_source("x\n", 0, 2, "auto", false, true).is_err());
        assert!(format_source("x\n", 80, 2, "windows", false, true).is_err());
    }
}
