# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib arity, .registration = TRUE
NULL

#' Format one R source string.
#' @keywords internal
format_text_native <- function(source, line_width, indent_width, line_ending, roxygen_markdown, verify) .Call(wrap__format_text_native, source, line_width, indent_width, line_ending, roxygen_markdown, verify)

#' Format one UTF-8 file in place and report whether it changed.
#' @keywords internal
format_file_native <- function(path, line_width, indent_width, line_ending, roxygen_markdown, verify) .Call(wrap__format_file_native, path, line_width, indent_width, line_ending, roxygen_markdown, verify)

# nolint end
